name: WebApp
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps:
      - uses: actions/checkout@master
      - name: Copy and rename env file
        run: |
          cp .env.example.js .env.js
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: actions/upload-artifact@v3
        if: github.event_name != 'pull_request'
        with:
          name: webapp
          path: web/.next
